# "데이터 분석 numpy 기초 문법 노트북"
> "2021년 여름방학 데이터분석을 위한 numpy 기초문법"

- toc:true
- branch: master
- badges: true
- comments: true
- author: Hamel Husain & Jeremy Howard
- categories: [fastpages, jupyter]

In [45]:
리스트 = [[1,2,3],[4,5,6],[7,8,9]]
리스트 = [0][0]
리스트 = [0]
리스트 = [2][0]
리스트*2

4

In [16]:
import numpy as np

리스트 = np.array(리스트)
리스트*2

4

In [19]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
a = np.arange(20).reshape(2,2,5)
a
a[0][1][2]

7

In [30]:
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size # flat한 데이터 사이즈
type(a)

numpy.ndarray

In [32]:
np.zeros((3, 4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((2, 3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [37]:
np.empty((2, 3))

array([[4.6412463e-310, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [39]:
np.arange(0, 2, 0.3) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [43]:
 np.linspace(0, 9.5, 20)  

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [46]:
np.linspace(0,5, 10, 20)  

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [59]:
rg = np.random.default_rng(1) 
rg

Generator(PCG64) at 0x7FC1FD086150

In [57]:
리스트 = [[10,2,3],[4,5,6],[7,8,9]]
a = np.array(리스트)
# a.sum(), sum(리스트) # sum(리스트)는 애러납니다
a.min(), min(리스트)
a.max, max(리스트) #2개는 출혁하는 결과도 다릅니다.


(<function ndarray.max>, [10, 2, 3])

In [53]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
b.sum(axis=0)  #col 기준으로 row끼리 더한것.(세로)
b.sum(axis=1)  #row 기준으로 col끼리 더한것.(가로)
b.sum()  #flat하게 모두 더한 것.

66

In [65]:
b.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
b.T #잘쓴다

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [79]:
a = np.array([[1,2],[3,4]])
b = np.floor([[5,6],[7,8]])
np.vstack((a, b))
np.hstack((a, b))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [77]:
# 매우 많이 사용
a = np.arange(12).reshape(3, 4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])